#!/bin/bash

if [[ "$#" -eq 0 ]]; then
  # `` allows to invoke the script
  # $# - number of params
  echo "Usage: `basename $0` command [args]"
  exit -1
fi


osascript <<- END
tell application "Terminal"
  do script "cd `pwd`; clear; $*; exit"
  activate
end tell
END
